//go:build windows

package etw

import (
	"fmt"
	"syscall"
	"unsafe"
)

// KERNEL_LOGGER_NAME
const (
	NtKernelLogger = "NT Kernel Logger"
	//  0x9e814aad, 0x3204, 0x11d2, 0x9a, 0x82, 0x00, 0x60, 0x08, 0xa8, 0x69, 0x39
)

// https://learn.microsoft.com/en-us/windows/win32/etw/msnt-systemtrace
var (
	//systemTraceControlGuid = MustParseGUIDFromString("{9E814AAD-3204-11D2-9A82-006008A86939}")
	// "Windows Kernel Trace" provider GUID (only one session can be running at any time)
	// If there is another session running that uses this GUID, the new session will stop the old one.
	systemTraceControlGuid = &GUID{ /* {9E814AAD-3204-11D2-9A82-006008A86939} */
		Data1: 0x9e814aad,
		Data2: 0x3204,
		Data3: 0x11d2,
		Data4: [8]byte{0x9a, 0x82, 0x00, 0x60, 0x08, 0xa8, 0x69, 0x39},
	}
)

// Trace Session interface
type Session interface {
	TraceName() string
	Providers() []Provider
	IsKernelSession() bool
}

// Real time Trace Session
type RealTimeSession struct {
	traceProps    *EventTracePropertyData2
	sessionHandle syscall.Handle

	traceName string
	providers []Provider
}

func (p *RealTimeSession) IsKernelSession() bool {
	return p.traceName == NtKernelLogger ||
		(p.traceProps.LogFileMode&EVENT_TRACE_SYSTEM_LOGGER_MODE) != 0
}

// NewRealTimeSession creates a new ETW trace session to receive events
// in real time
func NewRealTimeSession(name string) (s *RealTimeSession) {
	s = &RealTimeSession{}
	s.traceProps = NewRealTimeEventTraceProperties(name)
	s.traceName = name
	s.providers = make([]Provider, 0)
	return
}

// Only use this if the providers that will be enabled are not kernel providers
//
// NewPagedRealTimeSession creates a new ETW trace session to receive events
// in real time that uses paged memory.
// This setting is recommended so that events do not use up the nonpaged memory.
// Nonpaged buffers use nonpaged memory for buffer space.
// Because nonpaged buffers are never paged out, a logging session performs well.
// Using pageable buffers is less resource-intensive.
// Kernel-mode providers and system loggers cannot log events to sessions that specify this logging mode.
func NewPagedRealTimeSession(name string) (s *RealTimeSession) {
	s = NewRealTimeSession(name)
	s.traceProps.LogFileMode |= EVENT_TRACE_USE_PAGED_MEMORY
	return
}

// NewKernelRealTimeSession creates a new ETW trace system session to enable reading from the
// NT Kernel Logger trace events in real time (only one session can be running at any time)
//
// use: [GetKernelProviderFlags] for some predefined flags.
//
// To use a provider, you must enable it in the session creation
// like this:
//
//	kernelSession := etw.NewKernelRealTimeSession(etw.GetKernelProviderFlags("FileIo", "FileIoInit"))
//
// For File rundown events (opcode 36)
//
//	kernelSession := etw.NewKernelRealTimeSession(etw.GetKernelProviderFlags("DiskFileIo"))
//
// or
//
//	kernelSession := etw.NewKernelRealTimeSession(etw.EVENT_TRACE_FLAG_DISK_IO | etw.EVENT_TRACE_FLAG_DISK_FILE_IO)
//
// For a list of kernel providers use:
//
//	 for _, pd := range etw.KernelProviders {
//		 fmt.Printf("\t%s: %s\n", pd.Name, pd.GUID)
//	 }
//
// EnableFlags: https://learn.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-event_trace_properties EnableFlags section
//
// NOTE:
// These are legacy MOF type events. (without a manifest some of these event don't parse well)
// Most of the events properties that track something may have a zero value. (kernel memory)
//
// Some MOF are not documented on the microsoft site, for example: Process_V4_TypeGroup1 etc..
//
// https://msdn.microsoft.com/en-us/library/windows/desktop/aa364083(v=vs.85).aspx
func NewKernelRealTimeSession(flags ...uint32) (p *RealTimeSession) {
	p = NewRealTimeSession(NtKernelLogger)
	// guid must be set for Kernel Session
	p.traceProps.Wnode.Guid = *systemTraceControlGuid
	for _, flag := range flags {
		p.traceProps.EnableFlags |= flag
	}
	return
}

// TODO(tekert): import definitions.
//
// Warning!: needs Windows 10 SDK build 20348 or later, panics if not
//
// New way to enable kernel (now system) providers
// The events generated by the System Trace Provider are not changing due to this new feature.
// This means that the outputted events are not marked as being emitted from the individual
// system providers.
//
// https://learn.microsoft.com/en-us/windows/win32/etw/configuring-and-starting-a-systemtraceprovider-session
//
// # Starting a SystemTraceProvider Session using guids and keywords
//
// How to use it:
//   - GUIDs and Keywords defined here: https://learn.microsoft.com/en-us/windows/win32/etw/system-providers
//   - Write the keywords you want and put them in ParseProvider() wich are then passed to EnableTraceEx2
func NewSystemTraceProviderSession(name string) (s *RealTimeSession) {
	if IsWindowsVersionOrGreater(10, 0, 20348) {
		panic(fmt.Errorf("NewSystemTraceProviderSession requires " +
			"Windows 10 SDK build 20348 or later"))
	}

	s = NewRealTimeSession(name)
	s.traceProps.LogFileMode |= EVENT_TRACE_SYSTEM_LOGGER_MODE
	return
}

// TODO: remove logSessionName, no longer used.
func NewRealTimeEventTraceProperties(logSessionName string) *EventTracePropertyData2 {
	traceProps, size := NewEventTracePropertiesV2()

	// https://learn.microsoft.com/en-us/windows/win32/etw/wnode-header
	// Necessary fields for SessionProperties struct
	traceProps.Wnode.BufferSize = size // this is optimized by ETWframework
	traceProps.Wnode.Guid = GUID{}     // Will be set by etw
	// Only used if PROCESS_TRACE_MODE_RAW_TIMESTAMP is set in the Consumer side
	traceProps.Wnode.ClientContext = 1 // QPC
	// *NOTE(tekert) should this be WNODE_FLAG_TRACED_GUID instead of WNODE_FLAG_ALL_DATA?
	// WNODE_FLAG_VERSIONED_PROPERTIES means use EventTraceProperties2
	traceProps.Wnode.Flags = WNODE_FLAG_TRACED_GUID | WNODE_FLAG_VERSIONED_PROPERTIES
	traceProps.LogFileMode = EVENT_TRACE_REAL_TIME_MODE
	traceProps.LogFileNameOffset = 0
	//* ETW event can be up to 64KB size so if the buffer size is not at least
	// big enough to contain such an event, the event will be lost
	// source: https://docs.microsoft.com/en-us/message-analyzer/specifying-advanced-etw-session-configuration-settings
	traceProps.BufferSize = 64

	// StartTrace will copy the string for us.
	traceProps.LoggerNameOffset = traceProps.GetTraceNameOffset()

	return traceProps
}

// IsStarted returns true if the session is already started
func (s *RealTimeSession) IsStarted() bool {
	return s.sessionHandle != 0
}

// Start setups our session buffers so that providers can write to it
func (s *RealTimeSession) Start() (err error) {
	if s.IsStarted() {
		return
	}

	var u16TraceName *uint16
	if u16TraceName, err = syscall.UTF16PtrFromString(s.traceName); err != nil {
		return err
	}

	if s.IsKernelSession() {
		// Remove EVENT_TRACE_USE_PAGED_MEMORY flag from session properties
		s.traceProps.LogFileMode &= ^uint32(EVENT_TRACE_USE_PAGED_MEMORY)
	}

	traceProps := &s.traceProps.EventTraceProperties2
	if err = StartTrace(&s.sessionHandle, u16TraceName, traceProps); err != nil {
		// we handle the case where the trace already exists
		if err == ERROR_ALREADY_EXISTS {
			// we have to use a copy of properties as ControlTrace modifies
			// the structure and if we don't do that we cannot StartTrace later
			// the contigous memory space is not needed for this operation
			propCopy := *traceProps
			// we close the trace first
			ControlTrace(0, u16TraceName, &propCopy, EVENT_TRACE_CONTROL_STOP)
			return StartTrace(&s.sessionHandle, u16TraceName, traceProps)
		}
		return
	}

	return
}

// EnableProvider enables the trace session using [EnableTraceEx2]
// to receive events from a given provider
func (s *RealTimeSession) EnableProvider(prov Provider) (err error) {
	var guid *GUID

	// If the trace is not started yet we have to start it
	// otherwise we cannot enable provider
	if !s.IsStarted() {
		if err = s.Start(); err != nil {
			return
		}
	}

	guid = &prov.GUID

	params := EnableTraceParameters{
		Version: 2,
		// Does not seem to bring valuable information
		//EnableProperty: EVENT_ENABLE_PROPERTY_PROCESS_START_KEY,
	}

	if len(prov.Filter) > 0 {
		fds := prov.BuildFilterDesc()
		if len(fds) > 0 {
			params.EnableFilterDesc = (*EventFilterDescriptor)(unsafe.Pointer(&fds[0]))
			params.FilterDescCount = uint32(len(fds))
		}
	}

	if err = EnableTraceEx2(
		s.sessionHandle,
		guid,
		EVENT_CONTROL_CODE_ENABLE_PROVIDER,
		prov.EnableLevel,
		prov.MatchAnyKeyword,
		prov.MatchAllKeyword,
		0,
		&params,
	); err != nil {
		return
	}

	s.providers = append(s.providers, prov)

	return
}

// GetRundownEvents forces rundown events now.
// a null provider will force rundown for the system trace provider (NT Kernel Logger) (not fully tested)
// to capture the current state of the trace session
func (s *RealTimeSession) GetRundownEvents(prov *Provider) (err error) {
	if !s.IsStarted() {
		return fmt.Errorf("session not started")
	}
	guid := GUID{}
	if prov == nil {
		guid = *systemTraceControlGuid // TODO: not working, SystemConfig events are not delivered
	} else {
		guid = prov.GUID
	}

	if err = EnableTraceEx2(
		s.sessionHandle,
		&guid,
		EVENT_CONTROL_CODE_CAPTURE_STATE,
		0, 0, 0, 0, nil); err != nil {
		return
	}

	return nil
}

// TraceName implements Session interface
func (s *RealTimeSession) TraceName() string {
	return s.traceName
}

// Providers implements Session interface
func (s *RealTimeSession) Providers() []Provider {
	return s.providers
}

// Stop stops the session
// Blocks until all buffers are flushed and the session is fully stopped
func (s *RealTimeSession) Stop() error {
	return ControlTrace(s.sessionHandle, nil, &s.traceProps.EventTraceProperties2,
		EVENT_TRACE_CONTROL_STOP)
}

// Gets a copy of the current EventTraceProperties file used for this session
func (s *RealTimeSession) GetTracePropertyCopy() *EventTracePropertyData2 {
	return s.traceProps.Clone()
}

// Queries the current trace session to Get updated trace properties and stats.
// Don't modify the returned properties.
func (s *RealTimeSession) QueryTrace() (prop *EventTracePropertyData2, err error) {
	// If you are reusing a EVENT_TRACE_PROPERTIES structure
	// (i.e. using a structure that you previously passed to StartTrace or ControlTrace),
	// be sure to set the LogFileNameOffset member to 0 unless you are changing the log file name.
	s.traceProps.LogFileNameOffset = 0
	if err := ControlTrace(s.sessionHandle, nil, &s.traceProps.EventTraceProperties2,
		EVENT_TRACE_CONTROL_QUERY); err != nil {
		return nil, err
	}
	return s.traceProps, nil
}

// Flushes the session's active buffers.
// This will block until all buffers are flushed and the session is fully stopped
// If the session is not started, it returns an error.
func (s *RealTimeSession) Flush() error {
	if s.sessionHandle == 0 {
		return fmt.Errorf("session not started")
	}

	return ControlTrace(s.sessionHandle, nil, &s.traceProps.EventTraceProperties2,
		EVENT_TRACE_CONTROL_FLUSH)
}

// Provide a valid trace name
func NewQueryTraceProperties(traceName string) *EventTracePropertyData2 {
	traceProps, size := NewEventTracePropertiesV2()
	// Set only required fields for QUERY
	traceProps.Wnode.BufferSize = size
	traceProps.Wnode.Guid = GUID{}
	traceProps.SetTraceName(traceName)
	traceProps.LoggerNameOffset = traceProps.GetTraceNameOffset()
	traceProps.LogFileNameOffset = 0

	return traceProps
}

// Gets the properties of a realtime event trace session with instaceName (loggerName or traceName)
// logFileName not suported (sessions that write to a file)
// Use [NewQueryTraceProperties] output as parameter
func QueryTrace(queryProp *EventTracePropertyData2) (err error) {
	if queryProp == nil {
		return fmt.Errorf("data must be non nil")
	}
	instanceName := queryProp.GetTraceName()

	// If you are reusing a EVENT_TRACE_PROPERTIES structure
	// (i.e. using a structure that you previously passed to StartTrace or ControlTrace),
	// be sure to set the LogFileNameOffset member to 0 unless you are changing the log file name.
	queryProp.LogFileNameOffset = 0

	// There is no need to have the loggerName in queryProp.LoggerName
	// ControlTrace will set it for us on return. (instaceName -> quertProp.LoggerNameOffset)
	if err := ControlTrace(
		syscall.Handle(0),
		instanceName,
		&queryProp.EventTraceProperties2,
		EVENT_TRACE_CONTROL_QUERY); err != nil {
		return fmt.Errorf("ControlTrace query failed: %w", err)
	}
	return nil
}

// (used for internal debuggging)
func newQueryProperties2(tname string) *EventTracePropertyData2 {
	traceProps, size := NewEventTracePropertiesV2()
	// Set only required fields for QUERY
	traceProps.Wnode.BufferSize = size
	traceProps.Wnode.Guid = GUID{}

	traceProps.SetTraceName(tname)
	traceProps.LoggerNameOffset = traceProps.GetTraceNameOffset()
	traceProps.LogFileNameOffset = 0

	return traceProps
}

// Gets the properties of a trace session pointed by props
// Use a valid properties struct created with [NewQueryTraceProperties]
// The trace name is taken from props.LoggerNameOffset.
// (used for internal debuggging)
func queryTrace2(traceProps *EventTracePropertyData2) (err error) {
	// get loggerName from the props.LoggerNameOffset
	loggerName := traceProps.GetTraceName()

	// There is no need to have the loggerName in the properties
	// but we use for save us another parameter
	if err := ControlTrace(
		syscall.Handle(0),
		loggerName,
		&traceProps.EventTraceProperties2,
		EVENT_TRACE_CONTROL_QUERY); err != nil {
		return fmt.Errorf("ControlTrace query failed: %w", err)
	}
	return nil
}
